# Processing Modal Usaha

## Load the dataset

### Subtask:
Load the `nilai_modal_usaha_atas_izin_usaha_kecil_menurut_kabkota.csv` file into a pandas DataFrame.

**Reasoning**:
The subtask is to load a CSV file into a pandas DataFrame. The provided instructions outline the necessary steps: importing pandas, reading the CSV, and displaying the head of the DataFrame. These can be done in a single code block.

In [ ]:
import pandas as pd

df_modal_usaha = pd.read_csv('/content/nilai_modal_usaha_atas_izin_usaha_kecil_menurut_kabkota.csv')
display(df_modal_usaha.head())

,id,id_index,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,modal_usaha__triliun_rp_,periode_update,satuan,tahun
0,1,11,35,JAWA TIMUR,3526,KABUPATEN BANGKALAN,"0,03",2023-Q1,TRILIUN RUPIAH,2023
1,2,22,35,JAWA TIMUR,3510,KABUPATEN BANYUWANGI,"0,17",2023-Q1,TRILIUN RUPIAH,2023
2,3,33,35,JAWA TIMUR,3505,KABUPATEN BLITAR,"0,10",2023-Q1,TRILIUN RUPIAH,2023
3,4,44,35,JAWA TIMUR,3522,KABUPATEN BOJONEGORO,"0,14",2023-Q1,TRILIUN RUPIAH,2023
4,5,55,35,JAWA TIMUR,3511,KABUPATEN BONDOWOSO,"0,02",2023-Q1,TRILIUN RUPIAH,2023

## Clean 'modal usaha' column

### Subtask:
Convert the 'modal_usaha__triliun_rp_' column to a numeric type, handling the comma as a decimal separator.

**Reasoning**:
The task requires converting the 'modal_usaha__triliun_rp_' column to a numeric type, which involves replacing the comma decimal separator with a period and then casting the column to a numeric data type.

In [ ]:
df_modal_usaha['modal_usaha__triliun_rp_'] = df_modal_usaha['modal_usaha__triliun_rp_'].str.replace(',', '.', regex=False)
df_modal_usaha['modal_usaha__triliun_rp_'] = pd.to_numeric(df_modal_usaha['modal_usaha__triliun_rp_'])
display(df_modal_usaha.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        380 non-null    int64
 1   id_index                  380 non-null    int64
 2   kode_provinsi             380 non-null    int64
 3   nama_provinsi             380 non-null    object
 4   kode_kabupaten_kota       380 non-null    int64
 5   nama_kabupaten_kota       380 non-null    object
 6   modal_usaha__triliun_rp_  380 non-null    float64
 7   periode_update            380 non-null    object
 8   satuan                    380 non-null    object
 9   tahun                     380 non-null    int64
dtypes: float64(1), int64(5), object(4)
memory usage: 29.8+ KB

None

## Extract year

### Subtask:
Extract the year from the 'periode_update' column.

**Reasoning**:
Extract the year from the 'periode_update' column using string slicing and store it in a new 'tahun' column, then display the head of the DataFrame.

In [ ]:
df_modal_usaha['tahun'] = df_modal_usaha['periode_update'].astype(str).str[:4]
display(df_modal_usaha.head())

,id,id_index,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,modal_usaha__triliun_rp_,periode_update,satuan,tahun
0,1,11,35,JAWA TIMUR,3526,KABUPATEN BANGKALAN,0.03,2023-Q1,TRILIUN RUPIAH,2023
1,2,22,35,JAWA TIMUR,3510,KABUPATEN BANYUWANGI,0.17,2023-Q1,TRILIUN RUPIAH,2023
2,3,33,35,JAWA TIMUR,3505,KABUPATEN BLITAR,0.10,2023-Q1,TRILIUN RUPIAH,2023
3,4,44,35,JAWA TIMUR,3522,KABUPATEN BOJONEGORO,0.14,2023-Q1,TRILIUN RUPIAH,2023
4,5,55,35,JAWA TIMUR,3511,KABUPATEN BONDOWOSO,0.02,2023-Q1,TRILIUN RUPIAH,2023

## Aggregate data

### Subtask:
Group the DataFrame by 'nama_kabupaten_kota' and 'tahun' and sum the 'modal_usaha__triliun_rp_' to accumulate quarterly data.

**Reasoning**:
Group the DataFrame by 'nama_kabupaten_kota' and 'tahun' and sum the 'modal_usaha__triliun_rp_' to accumulate quarterly data.

In [ ]:
df_aggregated = df_modal_usaha.groupby(['nama_kabupaten_kota', 'tahun'])['modal_usaha__triliun_rp_'].sum().reset_index()
display(df_aggregated.head())

    nama_kabupaten_kota tahun  modal_usaha__triliun_rp_
0   KABUPATEN BANGKALAN  2023                      0.11
1   KABUPATEN BANGKALAN  2024                      0.14
2   KABUPATEN BANGKALAN  2025                      0.08
3  KABUPATEN BANYUWANGI  2023                      0.45
4  KABUPATEN BANYUWANGI  2024                      0.43

## Select and rename columns

### Subtask:
Select the aggregated 'nama_kabupaten_kota', the summed 'modal_usaha__triliun_rp_', and 'tahun' columns from `df_aggregated` and rename them to 'kabupaten/kota', 'modal usaha', and 'tahun' respectively.

**Reasoning**:
Select and rename the required columns from the aggregated DataFrame.

In [ ]:
df_processed = df_aggregated[['nama_kabupaten_kota', 'modal_usaha__triliun_rp_', 'tahun']].copy()
df_processed.rename(columns={'nama_kabupaten_kota': 'kabupaten/kota', 'modal_usaha__triliun_rp_': 'modal usaha'}, inplace=True)
display(df_processed.head())

         kabupaten/kota  modal usaha tahun
0   KABUPATEN BANGKALAN         0.11  2023
1   KABUPATEN BANGKALAN         0.14  2024
2   KABUPATEN BANGKALAN         0.08  2025
3  KABUPATEN BANYUWANGI         0.45  2023
4  KABUPATEN BANYUWANGI         0.43  2024

## Save the new dataset

### Subtask:
Save the processed DataFrame `df_processed` to a new CSV file named "processed_modal_usaha.csv".

**Reasoning**:
Save the processed DataFrame `df_processed` to a CSV file named "processed_modal_usaha.csv" without including the index.

In [ ]:
df_processed.to_csv('processed_modal_usaha.csv', index=False)

## Provide download link

### Subtask:
Generate a download link for the newly created CSV file, "processed_modal_usaha.csv".

**Reasoning**:
Use the `files.download` function to provide a download link for the created CSV file.

In [ ]:
from google.colab import files

files.download('processed_modal_usaha.csv')

## Summary:

### Data Analysis Key Findings

*   The original dataset contained quarterly data for modal usaha across different regencies/cities and years.
*   The `modal_usaha__triliun_rp_` column, initially stored as text with commas as decimal separators, was successfully converted to a numeric format (float64) by replacing commas with periods.
*   The year was successfully extracted from the `periode_update` column, allowing for aggregation by year.
*   The data was aggregated by `nama_kabupaten_kota` and `tahun`, summing the `modal_usaha__triliun_rp_` to provide the annual total modal usaha for each regency/city.
*   A new DataFrame was created with the required columns (`kabupaten/kota`, `modal usaha`, and `tahun`) and saved as "processed_modal_usaha.csv".

### Insights or Next Steps

*   The processed data provides a consolidated view of annual modal usaha per regency/city, which can be used for trend analysis or comparison between regions.
*   Further analysis could involve visualizing the modal usaha trends over time for different regencies/cities or comparing the total modal usaha across regions within a specific year.

#Master Dataset 2022

In [16]:
import sqlite3
import pandas as pd

# Create an in-memory SQLite database
conn = sqlite3.connect(':memory:')

try:
    df_dataset1 = pd.read_csv('/content/2022/Garis Kemiskinan Menurut Kabupaten_Kota di Jawa Timur, 2022.csv')
    df_dataset2 = pd.read_csv('/content/2022/Indeks Pembangunan Manusia (Hasil Long Form SP2020) Menurut Kabupaten_Kota, 2022.csv')
    df_dataset3 = pd.read_csv('/content/2022/Persentase Penduduk Miskin Menurut Kabupaten_Kota di Jawa Timur, 2022.csv')
    df_dataset4 = pd.read_csv('/content/2022/Modal_Usaha.csv')
    df_dataset5 = pd.read_csv('/content/2022/persentase_koperasi_aktif.csv')
    df_dataset6 = pd.read_csv('/content/persentase_usaha_mikro_dan_kecil.csv')
except FileNotFoundError:
    print("Make sure your CSV files are in the correct path.")
    # For demonstration, let's keep the sample dataframes if files are not found
    data1 = {'Kabupaten/Kota Se Jawa Timur': ['A', 'B', 'A', 'C'], 'col2': [1, 2, 3, 4]} # Added sample data for Kabupaten/Kota Se Jawa Timur
    df_dataset1 = pd.DataFrame(data1)

    data2 = {'Kabupaten/Kota Se Jawa Timur': ['A', 'B', 'D'], 'col3': ['X', 'Y', 'Z']} # Added sample data for Kabupaten/Kota Se Jawa Timur
    df_dataset2 = pd.DataFrame(data2)


# Load your DataFrames into the database as tables with simpler names
df_dataset1.to_sql('GarisKemiskinan_2022', conn, index=False, if_exists='replace')
df_dataset2.to_sql('IPM_2022', conn, index=False, if_exists='replace')
df_dataset3.to_sql('PersentaseKemiskinan_2022', conn, index=False, if_exists='replace')
df_dataset4.to_sql('Modal_Usaha', conn, index=False, if_exists='replace')
df_dataset5.to_sql('KoperasiAktif', conn, index=False, if_exists='replace')
df_dataset6.to_sql('PersenUsahaKecil', conn, index=False, if_exists='replace')

# Now you can perform SQL queries to recreate or create new datasets
# Example: Create a new dataset by selecting distinct kabupaten/kota and skipping None
query = """
SELECT
    gk."Kabupaten/Kota Se Jawa Timur" AS Nama_Kabupaten_Kota,
    gk."Garis Kemiskinan Menurut Kabupaten/Kota di Jawa Timur (Rupiah/Bulan/Kapita)" AS Garis_Kemiskinan_2022,
    ipm."Indeks Pembangunan Manusia (Hasil Long Form SP2020) Menurut Kabupaten/Kota" AS Indeks_Pembangunan_Manusia,
    pk."Persentase Penduduk Miskin Menurut Kabupaten/Kota di Jawa Timur (Persen)" AS Persen_Penduduk_Miskin,
    mu."modal_usaha" AS Nilai_Modal_Usaha_Kecil,
    ka."jumlah_koperasi_aktif" AS Persen_Koperasi_Aktif,
    pu."jumlah" AS Persen_UMK
FROM
    GarisKemiskinan_2022 AS gk -- Using the simpler table name
LEFT JOIN
    IPM_2022 AS ipm
ON
    gk."Kabupaten/Kota Se Jawa Timur" = ipm."Kabupaten/Kota Se Jawa Timur"
LEFT JOIN
    PersentaseKemiskinan_2022 AS pk
ON
    gk."Kabupaten/Kota Se Jawa Timur" = pk."Kab/Kota"
LEFT JOIN
    Modal_Usaha AS mu
ON
    gk."Kabupaten/Kota Se Jawa Timur" = mu."kabupaten/kota" AND mu.tahun = 2022
LEFT JOIN
    KoperasiAktif AS ka
ON gk."Kabupaten/Kota Se Jawa Timur" = ka."nama_kabupaten_kota" AND ka.kategori = 'PERSENTASE RAT' AND ka.tahun = 2022
LEFT JOIN
    PersenUsahaKecil AS pu
ON gk."Kabupaten/Kota Se Jawa Timur" = pu."nama_kabupaten_kota" AND pu.kategori = 'PERSENTASE USAHA KECIL' AND pu.tahun = 2022;
"""

# Execute the query and fetch the results into a new pandas DataFrame
master_dataset_2022_df = pd.read_sql_query(query, conn)

# Display the new dataset
display(master_dataset_2022_df)

# Close the connection when done
conn.close()

,Nama_Kabupaten_Kota,Garis_Kemiskinan_2022,Indeks_Pembangunan_Manusia,Persen_Penduduk_Miskin,Nilai_Modal_Usaha_Kecil,Persen_Koperasi_Aktif,Persen_UMK
0,Kabupaten Pacitan,327758,70.19,13.80,None,None,None
1,Kabupaten Ponorogo,362461,72.59,9.32,None,None,None
2,Kabupaten Trenggalek,381448,71.28,10.96,None,None,None
3,Kabupaten Tulungagung,391888,74.14,6.71,None,None,None
4,Kabupaten Blitar,355511,72.25,8.71,None,None,None
5,Kabupaten Kediri,353033,74.20,10.65,None,None,None
6,Kabupaten Malang,367579,72.23,9.55,None,None,None
7,Kabupaten Lumajang,352776,68.48,9.06,None,None,None
8,Kabupaten Jember,400961,69.80,9.39,None,None,None
9,Kabupaten Banyuwangi,414879,73.15,7.51,None,None,None
10,Kabupaten Bondowoso,449760,69.91,13.47,None,None,None
11,Kabupaten Situbondo,356133,69.76,11.78,None,None,None
12,Kabupaten Probolinggo,475713,69.56,17.12,None,None,None
13,Kabupaten Pasuruan,394016,71.29,8.96,None,None,None
14,Kabupaten Sidoarjo,523213,81.37,5.36,None,None,None
15,Kabupaten Mojokerto,445608,75.61,9.71,None,None,None
16,Kabupaten Jombang,448830,74.66,9.04,None,None,None
17,Kabupaten Nganjuk,474429,73.95,10.70,None,None,None
18,Kabupaten Madiun,405127,73.51,10.79,None,None,None
19,Kabupaten Magetan,396696,75.76,9.84,None,None,None
20,Kabupaten Ngawi,382301,72.62,14.15,None,None,None
21,Kabupaten Bojonegoro,403403,71.15,12.21,None,None,None
22,Kabupaten Tuban,421287,70.79,15.02,None,None,None
23,Kabupaten Lamongan,446601,74.83,12.53,None,None,None
24,Kabupaten Gresik,536544,77.62,11.06,None,None,None
25,Kabupaten Bangkalan,458754,66.11,19.44,None,None,None
26,Kabupaten Sampang,411661,65.44,21.61,None,None,None
27,Kabupaten Pamekasan,392345,69.35,13.93,None,None,None
28,Kabupaten Sumenep,427882,68.49,18.76,None,None,None
29,Kota Kediri,537326,80.12,7.23,None,None,None
30,Kota Blitar,517363,80.15,7.37,None,None,None
31,Kota Malang,609612,83.38,4.37,None,None,None
32,Kota Probolinggo,575195,76.08,6.65,None,None,None
33,Kota Pasuruan,486893,77.71,6.37,None,None,None
34,Kota Mojokerto,531804,80.19,5.98,None,None,None
35,Kota Madiun,551620,83.02,4.76,None,None,None
36,Kota Surabaya,652540,83.32,4.72,None,None,None
37,Kota Batu,564010,78.13,3.79,None,None,None
38,Jawa Timur,460909,74.05,NaN,None,None,None

In [17]:
from google.colab import files

# Save the master dataset to a CSV file
master_dataset_df.to_csv('master_dataset_2022.csv', index=False)

# Provide a download link for the CSV file
files.download('master_dataset_2022.csv')

#Master Dataset 2023

In [19]:
import sqlite3
import pandas as pd

# Create an in-memory SQLite database
conn = sqlite3.connect(':memory:')

try:
    df_dataseta1 = pd.read_csv('/content/2023/Garis Kemiskinan Menurut Kabupaten_Kota di Jawa Timur, 2023.csv')
    df_dataseta2 = pd.read_csv('/content/2023/Indeks Pembangunan Manusia (Hasil Long Form SP2020) Menurut Kabupaten_Kota, 2023.csv')
    df_dataseta3 = pd.read_csv('/content/2023/Persentase Penduduk Miskin Menurut Kabupaten_Kota di Jawa Timur, 2023.csv')
    df_dataseta4 = pd.read_csv('/content/2022/Modal_Usaha.csv')
    df_dataseta5 = pd.read_csv('/content/2022/persentase_koperasi_aktif.csv')
    df_dataseta6 = pd.read_csv('/content/persentase_usaha_mikro_dan_kecil.csv')
except FileNotFoundError:
    print("Make sure your CSV files are in the correct path.")
    # For demonstration, let's keep the sample dataframes if files are not found
    dataa1 = {'Kabupaten/Kota Se Jawa Timur': ['A', 'B', 'A', 'C'], 'col2': [1, 2, 3, 4]} # Added sample data for Kabupaten/Kota Se Jawa Timur
    df_dataseta1 = pd.DataFrame(dataa1)

    dataa2 = {'Kabupaten/Kota Se Jawa Timur': ['A', 'B', 'D'], 'col3': ['X', 'Y', 'Z']} # Added sample data for Kabupaten/Kota Se Jawa Timur
    df_dataseta2 = pd.DataFrame(dataa2)


# Load your DataFrames into the database as tables with simpler names
df_dataseta1.to_sql('GarisKemiskinan_2023', conn, index=False, if_exists='replace')
df_dataseta2.to_sql('IPM_2023', conn, index=False, if_exists='replace')
df_dataseta3.to_sql('PersentaseKemiskinan_2023', conn, index=False, if_exists='replace')
df_dataseta4.to_sql('Modal_Usaha', conn, index=False, if_exists='replace')
df_dataseta5.to_sql('KoperasiAktif', conn, index=False, if_exists='replace')
df_dataseta6.to_sql('PersenUsahaKecil', conn, index=False, if_exists='replace')

# Now you can perform SQL queries to recreate or create new datasets
# Example: Create a new dataset by selecting distinct kabupaten/kota and skipping None
query = """
SELECT
    gk."Kabupaten/Kota Se Jawa Timur" AS Nama_Kabupaten_Kota,
    gk."Garis Kemiskinan Menurut Kabupaten/Kota di Jawa Timur (Rupiah/Bulan/Kapita)" AS Garis_Kemiskinan_2023,
    ipm."Indeks Pembangunan Manusia (Hasil Long Form SP2020) Menurut Kabupaten/Kota" AS Indeks_Pembangunan_Manusia,
    pk."Persentase Penduduk Miskin Menurut Kabupaten/Kota di Jawa Timur (Persen)" AS Persen_Penduduk_Miskin,
    mu."modal_usaha" AS Nilai_Modal_Usaha_Kecil,
    ka."jumlah_koperasi_aktif" AS Persen_Koperasi_Aktif,
    pu."jumlah" AS Persen_UMK
FROM
    GarisKemiskinan_2023 AS gk -- Using the simpler table name
LEFT JOIN
    IPM_2023 AS ipm
ON
    gk."Kabupaten/Kota Se Jawa Timur" = ipm."Kabupaten/Kota Se Jawa Timur"
LEFT JOIN
    PersentaseKemiskinan_2023 AS pk
ON
    gk."Kabupaten/Kota Se Jawa Timur" = pk."Kab/Kota"
LEFT JOIN
    Modal_Usaha AS mu
ON
    gk."Kabupaten/Kota Se Jawa Timur" = mu."kabupaten/kota" AND mu.tahun = 2023
LEFT JOIN
    KoperasiAktif AS ka
ON gk."Kabupaten/Kota Se Jawa Timur" = ka."nama_kabupaten_kota" AND ka.kategori = 'PERSENTASE RAT' AND ka.tahun = 2023
LEFT JOIN
    PersenUsahaKecil AS pu
ON gk."Kabupaten/Kota Se Jawa Timur" = pu."nama_kabupaten_kota" AND pu.kategori = 'PERSENTASE USAHA KECIL' AND pu.tahun = 2023;
"""

# Execute the query and fetch the results into a new pandas DataFrame
master_dataset_2023_df = pd.read_sql_query(query, conn)

# Display the new dataset
display(master_dataset_2023_df)

# Close the connection when done
conn.close()

,Nama_Kabupaten_Kota,Garis_Kemiskinan_2023,Indeks_Pembangunan_Manusia,Persen_Penduduk_Miskin,Nilai_Modal_Usaha_Kecil,Persen_Koperasi_Aktif,Persen_UMK
0,Kabupaten Pacitan,352606,70.94,13.65,0.17,None,None
1,Kabupaten Ponorogo,395069,73.18,9.53,0.21,None,None
2,Kabupaten Trenggalek,411527,71.96,10.63,0.14,None,None
3,Kabupaten Tulungagung,423875,74.65,6.53,0.22,None,None
4,Kabupaten Blitar,387733,72.84,8.69,0.25,None,None
5,Kabupaten Kediri,385874,74.68,10.72,0.34,None,None
6,Kabupaten Malang,399647,73.00,9.45,0.78,None,None
7,Kabupaten Lumajang,386995,69.37,8.93,0.22,None,None
8,Kabupaten Jember,441171,70.42,9.51,0.63,None,None
9,Kabupaten Banyuwangi,448928,73.79,7.34,0.45,None,None
10,Kabupaten Bondowoso,494000,70.56,13.34,0.07,None,None
11,Kabupaten Situbondo,396587,70.65,11.90,0.17,None,None
12,Kabupaten Probolinggo,514274,70.36,17.19,0.20,None,None
13,Kabupaten Pasuruan,429624,71.91,9.24,0.55,None,None
14,Kabupaten Sidoarjo,571696,81.88,5.00,1.48,None,None
15,Kabupaten Mojokerto,486520,76.23,9.80,0.34,None,None
16,Kabupaten Jombang,488754,75.16,9.15,0.31,None,None
17,Kabupaten Nganjuk,513565,74.70,10.89,0.15,None,None
18,Kabupaten Madiun,437296,74.02,11.04,0.13,None,None
19,Kabupaten Magetan,431203,76.30,9.80,0.21,None,None
20,Kabupaten Ngawi,413947,73.28,14.40,0.20,None,None
21,Kabupaten Bojonegoro,435936,71.80,12.18,0.36,None,None
22,Kabupaten Tuban,454336,71.40,14.91,0.25,None,None
23,Kabupaten Lamongan,481969,75.29,12.42,0.24,None,None
24,Kabupaten Gresik,588316,78.44,10.96,0.60,None,None
25,Kabupaten Bangkalan,503207,66.82,19.35,0.11,None,None
26,Kabupaten Sampang,454716,66.19,21.76,0.09,None,None
27,Kabupaten Pamekasan,431127,70.32,13.85,0.18,None,None
28,Kabupaten Sumenep,471860,69.13,18.70,0.25,None,None
29,Kota Kediri,587723,80.97,7.15,0.21,None,None
30,Kota Blitar,568280,80.78,7.30,0.17,None,None
31,Kota Malang,674660,84.00,4.26,0.76,None,None
32,Kota Probolinggo,628380,76.93,6.48,0.14,None,None
33,Kota Pasuruan,529512,78.30,6.60,0.18,None,None
34,Kota Mojokerto,581006,80.90,5.77,0.08,None,None
35,Kota Madiun,605131,83.71,4.74,0.13,None,None
36,Kota Surabaya,718370,83.99,4.65,3.10,None,None
37,Kota Batu,613985,79.07,3.31,0.12,None,None
38,Jawa Timur,507286,74.65,10.35,NaN,None,None

In [20]:
from google.colab import files

# Save the master dataset to a CSV file
master_dataset_2023_df.to_csv('master_dataset_2023.csv', index=False)

# Provide a download link for the CSV file
files.download('master_dataset_2023.csv')

#Master Dataset 2024

In [23]:
import sqlite3
import pandas as pd

# Create an in-memory SQLite database
conn = sqlite3.connect(':memory:')

try:
    df_datasetab1 = pd.read_csv('/content/2024/Garis Kemiskinan Menurut Kabupaten_Kota di Jawa Timur, 2024.csv')
    df_datasetab2 = pd.read_csv('/content/2024/Indeks Pembangunan Manusia (Hasil Long Form SP2020) Menurut Kabupaten_Kota, 2024.csv')
    df_datasetab3 = pd.read_csv('/content/2024/Persentase Penduduk Miskin Menurut Kabupaten_Kota di Jawa Timur, 2024.csv')
    df_datasetab4 = pd.read_csv('/content/2022/Modal_Usaha.csv')
    df_datasetab5 = pd.read_csv('/content/2022/persentase_koperasi_aktif.csv')
    df_datasetab6 = pd.read_csv('/content/persentase_usaha_mikro_dan_kecil.csv')
except FileNotFoundError:
    print("Make sure your CSV files are in the correct path.")
    # For demonstration, let's keep the sample dataframes if files are not found
    dataab1 = {'Kabupaten/Kota Se Jawa Timur': ['A', 'B', 'A', 'C'], 'col2': [1, 2, 3, 4]} # Added sample data for Kabupaten/Kota Se Jawa Timur
    df_datasetab1 = pd.DataFrame(dataab1)

    dataab2 = {'Kabupaten/Kota Se Jawa Timur': ['A', 'B', 'D'], 'col3': ['X', 'Y', 'Z']} # Added sample data for Kabupaten/Kota Se Jawa Timur
    df_datasetab2 = pd.DataFrame(dataab2)


# Load your DataFrames into the database as tables with simpler names
df_datasetab1.to_sql('GarisKemiskinan_2024', conn, index=False, if_exists='replace')
df_datasetab2.to_sql('IPM_2024', conn, index=False, if_exists='replace')
df_datasetab3.to_sql('PersentaseKemiskinan_2024', conn, index=False, if_exists='replace')
df_datasetab4.to_sql('Modal_Usaha', conn, index=False, if_exists='replace')
df_datasetab5.to_sql('KoperasiAktif', conn, index=False, if_exists='replace')
df_datasetab6.to_sql('PersenUsahaKecil', conn, index=False, if_exists='replace')

# Now you can perform SQL queries to recreate or create new datasets
# Example: Create a new dataset by selecting distinct kabupaten/kota and skipping None
query = """
SELECT
    gk."Kabupaten/Kota Se Jawa Timur" AS Nama_Kabupaten_Kota,
    gk."Garis Kemiskinan Menurut Kabupaten/Kota di Jawa Timur (Rupiah/Bulan/Kapita)" AS Garis_Kemiskinan_2024,
    ipm."Indeks Pembangunan Manusia (Hasil Long Form SP2020) Menurut Kabupaten/Kota" AS Indeks_Pembangunan_Manusia,
    pk."Persentase Penduduk Miskin Menurut Kabupaten/Kota di Jawa Timur (Persen)" AS Persen_Penduduk_Miskin,
    mu."modal_usaha" AS Nilai_Modal_Usaha_Kecil,
    ka."jumlah_koperasi_aktif" AS Persen_Koperasi_Aktif,
    pu."jumlah" AS Persen_UMK
FROM
    GarisKemiskinan_2024 AS gk -- Using the simpler table name
LEFT JOIN
    IPM_2024 AS ipm
ON
    gk."Kabupaten/Kota Se Jawa Timur" = ipm."Kabupaten/Kota Se Jawa Timur"
LEFT JOIN
    PersentaseKemiskinan_2024 AS pk
ON
    gk."Kabupaten/Kota Se Jawa Timur" = pk."Kab/Kota"
LEFT JOIN
    Modal_Usaha AS mu
ON
    gk."Kabupaten/Kota Se Jawa Timur" = mu."kabupaten/kota" AND mu.tahun = 2024
LEFT JOIN
    KoperasiAktif AS ka
ON gk."Kabupaten/Kota Se Jawa Timur" = ka."nama_kabupaten_kota" AND ka.kategori = 'PERSENTASE RAT' AND ka.tahun = 2024
LEFT JOIN
    PersenUsahaKecil AS pu
ON gk."Kabupaten/Kota Se Jawa Timur" = pu."nama_kabupaten_kota" AND pu.kategori = 'PERSENTASE USAHA KECIL' AND pu.tahun = 2024;
"""

# Execute the query and fetch the results into a new pandas DataFrame
master_dataset_2024_df = pd.read_sql_query(query, conn)

# Display the new dataset
display(master_dataset_2024_df)

# Close the connection when done
conn.close()

,Nama_Kabupaten_Kota,Garis_Kemiskinan_2024,Indeks_Pembangunan_Manusia,Persen_Penduduk_Miskin,Nilai_Modal_Usaha_Kecil,Persen_Koperasi_Aktif,Persen_UMK
0,Kabupaten Pacitan,370643,71.49,13.08,0.08,34.51,0.01
1,Kabupaten Ponorogo,413619,73.70,9.11,0.14,36.62,0.08
2,Kabupaten Trenggalek,434146,72.47,10.50,0.12,37.34,0.00
3,Kabupaten Tulungagung,447793,75.13,6.28,0.33,25.29,0.02
4,Kabupaten Blitar,408399,73.44,8.16,0.17,NaN,NaN
5,Kabupaten Kediri,403621,75.18,9.95,0.37,NaN,NaN
6,Kabupaten Malang,420334,73.53,8.98,0.74,NaN,NaN
7,Kabupaten Lumajang,405136,70.31,8.65,0.16,48.80,0.04
8,Kabupaten Jember,459043,70.93,9.01,0.43,13.14,0.03
9,Kabupaten Banyuwangi,470713,74.30,6.54,0.43,27.24,0.04
10,Kabupaten Bondowoso,517741,71.22,12.60,0.09,12.17,0.01
11,Kabupaten Situbondo,413611,71.22,11.51,0.16,18.52,0.04
12,Kabupaten Probolinggo,537724,70.85,16.45,0.15,NaN,NaN
13,Kabupaten Pasuruan,450088,72.36,8.63,0.49,NaN,NaN
14,Kabupaten Sidoarjo,597284,82.67,4.53,1.20,30.25,0.07
15,Kabupaten Mojokerto,508618,76.69,9.37,0.29,NaN,NaN
16,Kabupaten Jombang,514170,75.67,8.60,0.26,49.83,0.04
17,Kabupaten Nganjuk,539714,75.24,10.17,0.10,30.61,0.07
18,Kabupaten Madiun,460205,74.81,10.63,0.18,NaN,NaN
19,Kabupaten Magetan,455119,76.77,9.32,0.09,35.85,0.02
20,Kabupaten Ngawi,445865,73.91,13.81,0.11,49.54,0.01
21,Kabupaten Bojonegoro,471457,72.75,11.69,0.27,22.41,0.04
22,Kabupaten Tuban,488131,72.31,14.36,0.22,36.10,0.01
23,Kabupaten Lamongan,524636,75.90,12.16,0.26,40.73,0.01
24,Kabupaten Gresik,608828,78.93,10.32,0.48,34.29,0.01
25,Kabupaten Bangkalan,547017,67.33,18.66,0.14,11.95,0.36
26,Kabupaten Sampang,491753,66.72,20.83,0.10,47.16,0.36
27,Kabupaten Pamekasan,467493,70.85,13.41,0.20,13.42,0.10
28,Kabupaten Sumenep,506569,69.78,17.78,0.17,9.97,0.07
29,Kota Kediri,621051,81.88,6.51,0.13,33.78,0.06
30,Kota Kediri,621051,81.88,6.51,0.13,33.78,1.36
31,Kota Kediri,621051,81.88,6.51,0.13,42.59,0.06
32,Kota Kediri,621051,81.88,6.51,0.13,42.59,1.36
33,Kota Blitar,596105,81.44,6.75,0.07,28.42,0.04
34,Kota Blitar,596105,81.44,6.75,0.07,28.42,1.22
35,Kota Blitar,596105,81.44,6.75,0.07,33.72,0.04
36,Kota Blitar,596105,81.44,6.75,0.07,33.72,1.22
37,Kota Malang,706341,84.68,3.91,0.69,32.94,0.03
38,Kota Malang,706341,84.68,3.91,0.69,32.94,0.12
39,Kota Malang,706341,84.68,3.91,0.69,52.83,0.03
40,Kota Malang,706341,84.68,3.91,0.69,52.83,0.12
41,Kota Probolinggo,654409,77.79,6.18,0.11,18.09,0.08
42,Kota Probolinggo,654409,77.79,6.18,0.11,18.09,1.09
43,Kota Probolinggo,654409,77.79,6.18,0.11,34.78,0.08
44,Kota Probolinggo,654409,77.79,6.18,0.11,34.78,1.09
45,Kota Pasuruan,554195,78.90,6.32,0.12,19.53,0.01
46,Kota Pasuruan,554195,78.90,6.32,0.12,19.53,0.74
47,Kota Pasuruan,554195,78.90,6.32,0.12,20.43,0.01
48,Kota Pasuruan,554195,78.90,6.32,0.12,20.43,0.74
49,Kota Mojokerto,610968,81.76,5.57,0.07,32.88,0.05
50,Kota Mojokerto,610968,81.76,5.57,0.07,32.88,1.36
51,Kota Mojokerto,610968,81.76,5.57,0.07,43.14,0.05
52,Kota Mojokerto,610968,81.76,5.57,0.07,43.14,1.36
53,Kota Madiun,637838,84.51,4.38,0.10,37.10,0.19
54,Kota Madiun,637838,84.51,4.38,0.10,37.10,1.14
55,Kota Madiun,637838,84.51,4.38,0.10,41.50,0.19
56,Kota Madiun,637838,84.51,4.38,0.10,41.50,1.14
57,Kota Surabaya,742678,84.69,3.96,2.58,24.89,0.03
58,Kota Batu,642778,79.69,3.06,0.13,36.36,0.97
59,Jawa Timur,536122,75.35,9.79,NaN,NaN,NaN

In [24]:
from google.colab import files

# Save the master dataset to a CSV file
master_dataset_2024_df.to_csv('master_dataset_2024.csv', index=False)

# Provide a download link for the CSV file
files.download('master_dataset_2024.csv')